#!/usr/bin/env python3

with open("title.bin", "wb") as OUTFILE:

	array = []
	with open("title.bmp", "rb") as INFILE:

		# Throw away the header
		bytedata = INFILE.read(82)

		# Everything else is pixel data
		for i in range(0, 200):

			# Print values for every byte in this row
			bytedata = INFILE.read(160)
			array.append(bytedata)

		for i in range(199, 0, -1):
			OUTFILE.write(array[i])
