#!/usr/bin/env python3

with open("title.bin", "rb") as FILE:

	for i in range(0, 199):

		# Print values for every byte in this row
		for j in range(160):
			bytedata = bytearray(FILE.read(1))
			value = bytedata[0]
			print(value)
